[build]
  command = "npm run build"
  publish = "apps/web/dist"

[functions]
  directory = "apps/api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
